<?xml version="1.0"?>
<package format="3">
  <name>roboai_bringup</name>
  <version>0.0.0</version>
  <description>RoboAI bringup package</description>
  <maintainer email="hbogdanov@todo.todo">hbogdanov</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>roboai_mapping</exec_depend>
  <exec_depend>roboai_frontier</exec_depend>
  <exec_depend>roboai_planning</exec_depend>
  <exec_depend>roboai_control</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
