<?xml version="1.0"?>
<package format="3">
  <name>roboai_mapping</name>
  <version>0.1.0</version>
  <description>RoboAI occupancy mapping node scaffold.</description>
  <maintainer email="ivan@example.com">Ivan</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
</package>
